version: 2
updates:
  - package-ecosystem: swift
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
  - package-ecosystem: swift
    directory: /Vendor/Citadel
    target-branch: develop
    schedule:
      interval: weekly
